### ISSUE TITLE
Ma zorcopio però mi gira le immagini

### ISSUE THREAD

**Issue by stephanNorsten** [AEEooTo/pindery#14]
For a strange unkown reason the app uploads the vertical images horizonatlly

**Comment by dedeswim** [comment]
It's solved, isn't it?

**Comment by stephanNorsten** [comment]
As we would say in Italy 

> "Manco per il cazzo"
cit.

But now I understood the problem: during the image compression the app loses the metadata about the rotation, it's already an issue of the original [library](https://github.com/brendan-duncan/image/issues/54)
