### ISSUE TITLE
Compress images before upload

### ISSUE THREAD

**Issue by dedeswim** [AEEooTo/pindery#7]
We should compress images before upload

**Comment by dedeswim** [comment]
Or maybe compress them right after the upload, using Firebase Cloud Functions?

**Comment by stephanNorsten** [comment]
I'm going to enhance the local compression before, for the rest we'll see

**Comment by dedeswim** [comment]
Actually compressing the image right after the upload would exepmt the device from the compressing task, while would increase the upload time. I sincerely don't know what would be better.
You're right, let's see how local compression works for now.

Do we want it working for Tier 1?

**Comment by stephanNorsten** [comment]
Fixed main issue.
Next step now: do not enlarge small pics.
